ignore:
  - "src/index.js"
  - "src/AuthProvider.js"
  - "src/reportWebVitals.js"
  - "src/Header.js"
  - "src/firebase.js"
  - "src/components/about"
  - "src/components/newsfeed/Newsfeed.js"
  - "src/components/features"
  - "src/components/userprofile"
  - "src/components/explore"
  - "src/components/post"
  - "src/components/newsfeed/Comment.js"
  - "src/components/newsfeed/SharedPost.js"
  - "src/components/newsfeed/SharedTopBar.js"
  - "src/components/newsfeed/Posts.js"
  - "src/components/common/Buttons.js"
  - "src/components/common/UserTopbar.js"
  - "src/components/common/RightSideBar.js"
  - "src/components/common/Users_Rsidebar.js"
  - "src/components/common/RightsidebarExplore.js"
  - "src/components/common"
  - "src/components/common/SidebarMenu.js"
  - "src/components/authentication/Login.js"
  - "src/components/authentication/Registration.js"
  - "src/App.js"
