ignore:
  - "src/index.js"
  - "src/Buttons.js"
  - "src/reportWebVitals.js"
  - "src/Header.js"
  - "src/firebase.js"
  - "src/components/about"
  - "src/components/newsfeed/Newsfeed.js"
  - "src/components/features"
  - "src/components/userprofile"
  - "src/components/explore"
