ignore:
  - "src/index.js"
  - "src/Buttons.js"
  - "src/reportWebVitals.js"
  - "src/Header.js"
  - "src/firebase.js"
  - "src/components/common"
  - "src/components/post"
  - "src/components/about"
  - "src/components/newsfeed"
